In [1]:
import numpy as np
import pandas as pd

import pandas_profiling

from sklearn.model_selection import train_test_split

from catboost import Pool, CatBoostRegressor

In [2]:
df = pd.read_csv("../data/train.csv")
df.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [3]:
df.profile_report(style={'full_width':True})

In [4]:
df.dtypes

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

In [5]:
df.iloc[:,np.where(df.dtypes == "object")[0]] = df.iloc[:,np.where(df.dtypes == "object")[0]].astype(str)

In [6]:
df = df.fillna(df.mean())

In [21]:
index = "Item_Identifier"
index1 = "Outlet_Identifier"
label = "Item_Outlet_Sales"
X = df.drop([index, label], axis=1)
# X = df[features]
y = df[label]
X.dtypes

Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
dtype: object

In [8]:
categorical_features_indices = np.where(X.dtypes == "object")[0]
categorical_features_indices

array([1, 3, 5, 7, 8, 9])

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
# clf = RandomForestClassifier()
clf = CatBoostRegressor()

In [12]:
clf.fit(X_train, y_train,cat_features=categorical_features_indices)

0:	learn: 2737.3319308	total: 3.97ms	remaining: 3.97s
1:	learn: 2670.6505368	total: 14.1ms	remaining: 7.05s
2:	learn: 2607.0750559	total: 20.3ms	remaining: 6.74s
3:	learn: 2544.3174252	total: 26.6ms	remaining: 6.62s
4:	learn: 2485.3554373	total: 33ms	remaining: 6.56s
5:	learn: 2429.2957447	total: 39.3ms	remaining: 6.52s
6:	learn: 2373.0974762	total: 46.3ms	remaining: 6.56s
7:	learn: 2319.2947910	total: 52.5ms	remaining: 6.51s
8:	learn: 2267.4695218	total: 63ms	remaining: 6.94s
9:	learn: 2217.2812436	total: 77.3ms	remaining: 7.65s
10:	learn: 2171.1205003	total: 87ms	remaining: 7.82s
11:	learn: 2124.7273186	total: 102ms	remaining: 8.37s
12:	learn: 2082.9166202	total: 112ms	remaining: 8.53s
13:	learn: 2039.7795164	total: 118ms	remaining: 8.32s
14:	learn: 1999.2165259	total: 122ms	remaining: 8.03s
15:	learn: 1961.2496620	total: 128ms	remaining: 7.87s
16:	learn: 1924.8114540	total: 132ms	remaining: 7.63s
17:	learn: 1888.8394258	total: 139ms	remaining: 7.56s
18:	learn: 1854.2424332	total: 14

167:	learn: 1080.7451657	total: 1.43s	remaining: 7.08s
168:	learn: 1080.6475578	total: 1.44s	remaining: 7.06s
169:	learn: 1080.6123883	total: 1.44s	remaining: 7.04s
170:	learn: 1080.5271776	total: 1.45s	remaining: 7.04s
171:	learn: 1080.3869727	total: 1.47s	remaining: 7.06s
172:	learn: 1080.3274966	total: 1.47s	remaining: 7.04s
173:	learn: 1080.1694646	total: 1.49s	remaining: 7.05s
174:	learn: 1080.1323062	total: 1.49s	remaining: 7.04s
175:	learn: 1080.0587225	total: 1.5s	remaining: 7.04s
176:	learn: 1079.9842399	total: 1.51s	remaining: 7.03s
177:	learn: 1079.9429477	total: 1.52s	remaining: 7s
178:	learn: 1079.7687167	total: 1.53s	remaining: 7s
179:	learn: 1079.6998032	total: 1.53s	remaining: 6.97s
180:	learn: 1079.5781340	total: 1.53s	remaining: 6.95s
181:	learn: 1079.5471404	total: 1.54s	remaining: 6.91s
182:	learn: 1079.5449512	total: 1.54s	remaining: 6.87s
183:	learn: 1079.5296411	total: 1.54s	remaining: 6.83s
184:	learn: 1079.2929860	total: 1.55s	remaining: 6.82s
185:	learn: 1079.

333:	learn: 1071.3820821	total: 2.63s	remaining: 5.24s
334:	learn: 1071.3519398	total: 2.63s	remaining: 5.23s
335:	learn: 1071.3324313	total: 2.64s	remaining: 5.22s
336:	learn: 1071.2406941	total: 2.65s	remaining: 5.21s
337:	learn: 1071.1642964	total: 2.66s	remaining: 5.2s
338:	learn: 1070.9816792	total: 2.67s	remaining: 5.2s
339:	learn: 1070.9122010	total: 2.68s	remaining: 5.2s
340:	learn: 1070.5656417	total: 2.7s	remaining: 5.22s
341:	learn: 1070.3897558	total: 2.71s	remaining: 5.22s
342:	learn: 1070.3572004	total: 2.73s	remaining: 5.22s
343:	learn: 1070.2866983	total: 2.73s	remaining: 5.22s
344:	learn: 1070.2816186	total: 2.74s	remaining: 5.2s
345:	learn: 1070.2455932	total: 2.75s	remaining: 5.19s
346:	learn: 1070.1876667	total: 2.76s	remaining: 5.19s
347:	learn: 1069.9632670	total: 2.77s	remaining: 5.19s
348:	learn: 1069.8128614	total: 2.78s	remaining: 5.19s
349:	learn: 1069.5941478	total: 2.79s	remaining: 5.19s
350:	learn: 1069.4146059	total: 2.81s	remaining: 5.19s
351:	learn: 106

501:	learn: 1055.1731879	total: 4.46s	remaining: 4.42s
502:	learn: 1055.1626816	total: 4.47s	remaining: 4.42s
503:	learn: 1055.0880518	total: 4.49s	remaining: 4.41s
504:	learn: 1054.9109216	total: 4.5s	remaining: 4.41s
505:	learn: 1054.8697691	total: 4.51s	remaining: 4.4s
506:	learn: 1054.7974304	total: 4.51s	remaining: 4.39s
507:	learn: 1054.7370570	total: 4.52s	remaining: 4.38s
508:	learn: 1054.7077068	total: 4.54s	remaining: 4.38s
509:	learn: 1054.6379477	total: 4.55s	remaining: 4.37s
510:	learn: 1054.6304851	total: 4.56s	remaining: 4.36s
511:	learn: 1054.6267756	total: 4.57s	remaining: 4.35s
512:	learn: 1054.4439078	total: 4.57s	remaining: 4.34s
513:	learn: 1054.3150969	total: 4.58s	remaining: 4.33s
514:	learn: 1054.2798224	total: 4.59s	remaining: 4.33s
515:	learn: 1054.1197885	total: 4.61s	remaining: 4.32s
516:	learn: 1054.0005322	total: 4.61s	remaining: 4.31s
517:	learn: 1053.9435148	total: 4.62s	remaining: 4.3s
518:	learn: 1053.7962406	total: 4.63s	remaining: 4.29s
519:	learn: 1

651:	learn: 1045.0691917	total: 6.1s	remaining: 3.25s
652:	learn: 1045.0526275	total: 6.11s	remaining: 3.25s
653:	learn: 1044.9002469	total: 6.12s	remaining: 3.24s
654:	learn: 1044.7793131	total: 6.13s	remaining: 3.23s
655:	learn: 1044.7750906	total: 6.13s	remaining: 3.22s
656:	learn: 1044.7564760	total: 6.14s	remaining: 3.21s
657:	learn: 1044.7465750	total: 6.16s	remaining: 3.2s
658:	learn: 1044.6613896	total: 6.17s	remaining: 3.19s
659:	learn: 1044.6039947	total: 6.18s	remaining: 3.19s
660:	learn: 1044.5135792	total: 6.19s	remaining: 3.17s
661:	learn: 1044.4421764	total: 6.2s	remaining: 3.17s
662:	learn: 1044.4363778	total: 6.21s	remaining: 3.16s
663:	learn: 1044.3622241	total: 6.22s	remaining: 3.15s
664:	learn: 1044.3055267	total: 6.23s	remaining: 3.14s
665:	learn: 1044.2980889	total: 6.24s	remaining: 3.13s
666:	learn: 1044.2644455	total: 6.25s	remaining: 3.12s
667:	learn: 1044.2387630	total: 6.26s	remaining: 3.11s
668:	learn: 1044.0515519	total: 6.27s	remaining: 3.1s
669:	learn: 10

808:	learn: 1035.6044309	total: 7.95s	remaining: 1.88s
809:	learn: 1035.5615423	total: 7.96s	remaining: 1.87s
810:	learn: 1035.5292065	total: 7.98s	remaining: 1.86s
811:	learn: 1035.5155188	total: 7.99s	remaining: 1.85s
812:	learn: 1035.4937002	total: 8.01s	remaining: 1.84s
813:	learn: 1035.4571508	total: 8.02s	remaining: 1.83s
814:	learn: 1035.4201182	total: 8.04s	remaining: 1.82s
815:	learn: 1035.3478104	total: 8.04s	remaining: 1.81s
816:	learn: 1035.2785144	total: 8.05s	remaining: 1.8s
817:	learn: 1035.2422239	total: 8.06s	remaining: 1.79s
818:	learn: 1035.2185176	total: 8.08s	remaining: 1.78s
819:	learn: 1035.2092351	total: 8.09s	remaining: 1.77s
820:	learn: 1035.1941947	total: 8.1s	remaining: 1.76s
821:	learn: 1035.0303647	total: 8.12s	remaining: 1.76s
822:	learn: 1035.0250299	total: 8.12s	remaining: 1.75s
823:	learn: 1035.0222859	total: 8.13s	remaining: 1.74s
824:	learn: 1034.8720594	total: 8.15s	remaining: 1.73s
825:	learn: 1034.7575081	total: 8.16s	remaining: 1.72s
826:	learn: 

966:	learn: 1026.8235432	total: 9.79s	remaining: 334ms
967:	learn: 1026.7902149	total: 9.8s	remaining: 324ms
968:	learn: 1026.7532420	total: 9.81s	remaining: 314ms
969:	learn: 1026.7367012	total: 9.82s	remaining: 304ms
970:	learn: 1026.6619999	total: 9.83s	remaining: 294ms
971:	learn: 1026.6345350	total: 9.84s	remaining: 284ms
972:	learn: 1026.5943673	total: 9.86s	remaining: 274ms
973:	learn: 1026.5875279	total: 9.87s	remaining: 264ms
974:	learn: 1026.5814271	total: 9.88s	remaining: 253ms
975:	learn: 1026.5037007	total: 9.89s	remaining: 243ms
976:	learn: 1026.4976084	total: 9.9s	remaining: 233ms
977:	learn: 1026.3033381	total: 9.92s	remaining: 223ms
978:	learn: 1026.1885858	total: 9.94s	remaining: 213ms
979:	learn: 1026.1665559	total: 9.96s	remaining: 203ms
980:	learn: 1026.1619608	total: 9.97s	remaining: 193ms
981:	learn: 1026.1473771	total: 9.99s	remaining: 183ms
982:	learn: 1026.1432732	total: 10s	remaining: 173ms
983:	learn: 1026.1425618	total: 10s	remaining: 163ms
984:	learn: 1026

In [14]:
score = clf.score(X_test, y_test)
score

0.5993512450589358

In [15]:
clf.fit(X, y, cat_features=categorical_features_indices)

0:	learn: 2702.0925041	total: 20.6ms	remaining: 20.5s
1:	learn: 2636.9560999	total: 40.1ms	remaining: 20s
2:	learn: 2575.0169636	total: 49ms	remaining: 16.3s
3:	learn: 2513.5464321	total: 57.1ms	remaining: 14.2s
4:	learn: 2455.6357514	total: 65ms	remaining: 12.9s
5:	learn: 2398.7484421	total: 73.3ms	remaining: 12.2s
6:	learn: 2344.2832405	total: 81.1ms	remaining: 11.5s
7:	learn: 2291.0444393	total: 89.2ms	remaining: 11.1s
8:	learn: 2241.2590727	total: 99.7ms	remaining: 11s
9:	learn: 2193.1331335	total: 114ms	remaining: 11.3s
10:	learn: 2147.0065345	total: 130ms	remaining: 11.7s
11:	learn: 2101.2586769	total: 144ms	remaining: 11.8s
12:	learn: 2056.8758497	total: 152ms	remaining: 11.5s
13:	learn: 2014.7294456	total: 160ms	remaining: 11.3s
14:	learn: 1973.8122808	total: 168ms	remaining: 11s
15:	learn: 1934.0566312	total: 176ms	remaining: 10.8s
16:	learn: 1897.4418745	total: 181ms	remaining: 10.5s
17:	learn: 1862.1945965	total: 189ms	remaining: 10.3s
18:	learn: 1826.6857986	total: 197ms	re

168:	learn: 1071.2806234	total: 1.86s	remaining: 9.15s
169:	learn: 1071.2128580	total: 1.87s	remaining: 9.13s
170:	learn: 1071.1390437	total: 1.89s	remaining: 9.14s
171:	learn: 1071.1052900	total: 1.89s	remaining: 9.12s
172:	learn: 1071.0372818	total: 1.9s	remaining: 9.08s
173:	learn: 1071.0238721	total: 1.91s	remaining: 9.06s
174:	learn: 1070.9948860	total: 1.91s	remaining: 9.01s
175:	learn: 1070.8087423	total: 1.93s	remaining: 9.03s
176:	learn: 1070.7908061	total: 1.94s	remaining: 9.02s
177:	learn: 1070.7780519	total: 1.95s	remaining: 9s
178:	learn: 1070.6305226	total: 1.97s	remaining: 9.02s
179:	learn: 1070.6191981	total: 1.98s	remaining: 9s
180:	learn: 1070.5319921	total: 1.99s	remaining: 9.01s
181:	learn: 1070.5079574	total: 1.99s	remaining: 8.96s
182:	learn: 1070.4309314	total: 2s	remaining: 8.94s
183:	learn: 1070.3622487	total: 2.02s	remaining: 8.94s
184:	learn: 1070.2822709	total: 2.03s	remaining: 8.93s
185:	learn: 1070.1385236	total: 2.05s	remaining: 8.96s
186:	learn: 1070.106

322:	learn: 1065.2946669	total: 3.29s	remaining: 6.91s
323:	learn: 1065.0974188	total: 3.31s	remaining: 6.91s
324:	learn: 1065.0176178	total: 3.33s	remaining: 6.91s
325:	learn: 1064.8712851	total: 3.35s	remaining: 6.93s
326:	learn: 1064.8560018	total: 3.37s	remaining: 6.92s
327:	learn: 1064.8426527	total: 3.37s	remaining: 6.9s
328:	learn: 1064.7483441	total: 3.38s	remaining: 6.9s
329:	learn: 1064.7483439	total: 3.39s	remaining: 6.88s
330:	learn: 1064.7037063	total: 3.4s	remaining: 6.87s
331:	learn: 1064.6464731	total: 3.41s	remaining: 6.87s
332:	learn: 1064.6444521	total: 3.42s	remaining: 6.84s
333:	learn: 1064.6266394	total: 3.43s	remaining: 6.84s
334:	learn: 1064.5538727	total: 3.46s	remaining: 6.86s
335:	learn: 1064.5538726	total: 3.46s	remaining: 6.84s
336:	learn: 1064.4425641	total: 3.47s	remaining: 6.82s
337:	learn: 1064.4072679	total: 3.48s	remaining: 6.82s
338:	learn: 1064.4052552	total: 3.48s	remaining: 6.8s
339:	learn: 1064.4033223	total: 3.49s	remaining: 6.77s
340:	learn: 10

483:	learn: 1057.3948984	total: 5.13s	remaining: 5.46s
484:	learn: 1057.3515244	total: 5.15s	remaining: 5.47s
485:	learn: 1057.3052264	total: 5.16s	remaining: 5.46s
486:	learn: 1057.2580380	total: 5.18s	remaining: 5.45s
487:	learn: 1057.1422268	total: 5.18s	remaining: 5.44s
488:	learn: 1057.1168140	total: 5.19s	remaining: 5.43s
489:	learn: 1057.0187794	total: 5.21s	remaining: 5.42s
490:	learn: 1057.0183397	total: 5.21s	remaining: 5.4s
491:	learn: 1056.9730975	total: 5.22s	remaining: 5.39s
492:	learn: 1056.9719159	total: 5.23s	remaining: 5.38s
493:	learn: 1056.9714935	total: 5.23s	remaining: 5.36s
494:	learn: 1056.9706633	total: 5.24s	remaining: 5.34s
495:	learn: 1056.8400575	total: 5.25s	remaining: 5.34s
496:	learn: 1056.8396589	total: 5.25s	remaining: 5.32s
497:	learn: 1056.8060464	total: 5.27s	remaining: 5.31s
498:	learn: 1056.8029344	total: 5.28s	remaining: 5.3s
499:	learn: 1056.7503382	total: 5.29s	remaining: 5.29s
500:	learn: 1056.7190362	total: 5.3s	remaining: 5.28s
501:	learn: 1

642:	learn: 1048.9160766	total: 7.18s	remaining: 3.99s
643:	learn: 1048.8751911	total: 7.19s	remaining: 3.98s
644:	learn: 1048.8705103	total: 7.21s	remaining: 3.97s
645:	learn: 1048.8264747	total: 7.22s	remaining: 3.96s
646:	learn: 1048.6762591	total: 7.23s	remaining: 3.94s
647:	learn: 1048.5342220	total: 7.24s	remaining: 3.93s
648:	learn: 1048.4521174	total: 7.25s	remaining: 3.92s
649:	learn: 1048.4185781	total: 7.26s	remaining: 3.91s
650:	learn: 1048.4150214	total: 7.28s	remaining: 3.9s
651:	learn: 1048.3916125	total: 7.3s	remaining: 3.9s
652:	learn: 1048.3350069	total: 7.32s	remaining: 3.89s
653:	learn: 1048.3257952	total: 7.33s	remaining: 3.88s
654:	learn: 1048.2967342	total: 7.35s	remaining: 3.87s
655:	learn: 1048.1998408	total: 7.36s	remaining: 3.86s
656:	learn: 1048.1714303	total: 7.38s	remaining: 3.85s
657:	learn: 1048.0811525	total: 7.39s	remaining: 3.84s
658:	learn: 1047.8966180	total: 7.41s	remaining: 3.83s
659:	learn: 1047.8288456	total: 7.42s	remaining: 3.82s
660:	learn: 1

794:	learn: 1041.7682148	total: 9.23s	remaining: 2.38s
795:	learn: 1041.7366077	total: 9.25s	remaining: 2.37s
796:	learn: 1041.7126315	total: 9.26s	remaining: 2.36s
797:	learn: 1041.7049564	total: 9.28s	remaining: 2.35s
798:	learn: 1041.7047030	total: 9.29s	remaining: 2.34s
799:	learn: 1041.6701087	total: 9.3s	remaining: 2.33s
800:	learn: 1041.5995692	total: 9.31s	remaining: 2.31s
801:	learn: 1041.5993305	total: 9.32s	remaining: 2.3s
802:	learn: 1041.5313429	total: 9.34s	remaining: 2.29s
803:	learn: 1041.3886825	total: 9.35s	remaining: 2.28s
804:	learn: 1041.3355678	total: 9.36s	remaining: 2.27s
805:	learn: 1041.3016555	total: 9.37s	remaining: 2.25s
806:	learn: 1041.3001084	total: 9.39s	remaining: 2.25s
807:	learn: 1041.2196853	total: 9.4s	remaining: 2.23s
808:	learn: 1041.2196223	total: 9.41s	remaining: 2.22s
809:	learn: 1041.1775872	total: 9.43s	remaining: 2.21s
810:	learn: 1041.1547133	total: 9.44s	remaining: 2.2s
811:	learn: 1041.1056780	total: 9.46s	remaining: 2.19s
812:	learn: 10

949:	learn: 1034.6817939	total: 11.3s	remaining: 597ms
950:	learn: 1034.5719280	total: 11.4s	remaining: 585ms
951:	learn: 1034.5713769	total: 11.4s	remaining: 573ms
952:	learn: 1034.5281577	total: 11.4s	remaining: 561ms
953:	learn: 1034.4547692	total: 11.4s	remaining: 549ms
954:	learn: 1034.4164816	total: 11.4s	remaining: 537ms
955:	learn: 1034.3659217	total: 11.4s	remaining: 525ms
956:	learn: 1034.2142926	total: 11.4s	remaining: 514ms
957:	learn: 1034.2142479	total: 11.4s	remaining: 502ms
958:	learn: 1034.1251105	total: 11.5s	remaining: 490ms
959:	learn: 1034.1195270	total: 11.5s	remaining: 478ms
960:	learn: 1034.0449166	total: 11.5s	remaining: 467ms
961:	learn: 1034.0439848	total: 11.5s	remaining: 455ms
962:	learn: 1034.0319577	total: 11.5s	remaining: 443ms
963:	learn: 1034.0074646	total: 11.5s	remaining: 431ms
964:	learn: 1033.9560668	total: 11.6s	remaining: 419ms
965:	learn: 1033.9548928	total: 11.6s	remaining: 407ms
966:	learn: 1033.9475125	total: 11.6s	remaining: 395ms
967:	learn

In [38]:
df_pred = pd.read_csv("../data/test.csv")
df_pred = df_pred.fillna(df_pred.mean())
df_pred = df_pred.fillna(df_pred.mode().iloc[0])

X_pred = df_pred.drop([index], axis=1)
y_pred = clf.predict(X_pred)
df_pred[label] = (y_pred + 0.5).astype(int)
df_submission = df_pred[[index, index1, label]]
df_submission.to_csv("../data/pred.csv", index=False)

In [34]:
df_submission.shape

(5681, 3)

In [36]:
df_sample = pd.read_csv("../data/sample.csv")
df_sample.shape

(5681, 3)

In [29]:
np.around(y_pred + 0.5, decimals=-1)

array([1760., 1350.,  700., ..., 1800., 3760., 1280.])

In [31]:
y_pred

array([1759.66115418, 1351.07949026,  700.92663596, ..., 1795.34587982,
       3757.20543481, 1281.09635707])

In [32]:
(y_pred + 0.5).astype(int)

array([1760, 1351,  701, ..., 1795, 3757, 1281])